const { ethers } = require('ethers');
const fs = require('fs');
const path = require('path');

// Load contract data (generated by deploy script)
// Load contract data (generated by deploy_v2 script)
// Note: We are using a different file structure for V2. 
// Ideally we should unify, but for this upgrade we'll look for the frontend config first.
const frontendConfigPath = path.resolve(__dirname, '../../frontend/js/contract-config-v3.json');

let loggerContract;
let nftContract;
let tokenContract;
let identityContract;
let provider;
let wallet;

const initBlockchain = async () => {
    try {
        console.log(`Checking for blockchain V3 config at: ${frontendConfigPath}`);

        // 1. Retry Logic for Config
        if (!fs.existsSync(frontendConfigPath)) {
            console.warn('Config not found immediately. Retrying in 3 seconds...');
            await new Promise(resolve => setTimeout(resolve, 3000));
            if (!fs.existsSync(frontendConfigPath)) {
                console.warn('Blockchain V3 config still not found. Blockchain features disabled.');
                return;
            }
        }

        let config;
        try {
            config = JSON.parse(fs.readFileSync(frontendConfigPath, 'utf8'));
        } catch (readError) {
            console.error('Error parsing blockchain config:', readError);
            return;
        }

        // Connect to local Hardhat node
        provider = new ethers.JsonRpcProvider(process.env.BLOCKCHAIN_RPC_URL || 'http://127.0.0.1:8545');

        // Use the first account from Hardhat node
        const privateKey = process.env.BLOCKCHAIN_PRIVATE_KEY || '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80';
        wallet = new ethers.Wallet(privateKey, provider);

        // ABIs (Minimal for interaction)
        const loggerAbi = ["function logAttempt(string memory userId, string memory quizId, uint256 score, uint256 timestamp) public returns (uint256)"];
        const nftAbi = ["function mintCertificate(address recipient, string memory tokenURI, string memory studentName, string memory courseName, uint256 score) public returns (uint256)"];
        const tokenAbi = ["function mint(address to, uint256 amount) public", "function balanceOf(address account) view returns (uint256)"];
        const identityAbi = ["function registerIdentity(string memory _did, string memory _profileHash) public", "function getIdentity(address _user) view returns (tuple(string did, string profileHash, bool isVerified, uint256 verificationDate))"];

        loggerContract = new ethers.Contract(config.quizLoggerAddress, loggerAbi, wallet);
        nftContract = new ethers.Contract(config.certificateNFTAddress, nftAbi, wallet);
        tokenContract = new ethers.Contract(config.tidalTokenAddress, tokenAbi, wallet);
        identityContract = new ethers.Contract(config.academicIdentityAddress, identityAbi, wallet);

        console.log('Blockchain service V3 initialized successfully');

    } catch (error) {
        console.error('CRITICAL ERROR initializing blockchain service:', error);
    }
};

const logAttemptToBlockchain = async (userId, quizId, score, timestamp) => {
    if (!loggerContract) {
        console.warn('Blockchain contract not initialized.');
        return null;
    }

    try {
        const tx = await loggerContract.logAttempt(userId.toString(), quizId.toString(), score, timestamp);
        console.log(`[DEBUG] Blockchain TX sent: ${tx.hash}`);
        await tx.wait();
        console.log(`[DEBUG] Blockchain TX confirmed: ${tx.hash}`);
        return tx.hash;
    } catch (error) {
        console.error('[DEBUG] Error logging to blockchain:', error.message);
        if (error.code) console.error('[DEBUG] Error Code:', error.code);
        if (error.reason) console.error('[DEBUG] Error Reason:', error.reason);
        return null;
    }
};

const mintCertificateNFT = async (recipientAddress, studentName, quizTitle, score) => {
    if (!nftContract) {
        console.warn('NFT contract not ready. Attempting lazy init...');
        await initBlockchain();
        if (!nftContract) {
            console.error('Blockchain Service Unavailable.');
            return null;
        }
    }
    try {
        // Metadata URI (mock for now, usually IPFS)
        const tokenURI = `https://api.ai-proctroing-exam.edu/certificates/${Date.now()}.json`;

        const tx = await nftContract.mintCertificate(recipientAddress, tokenURI, studentName, quizTitle, score);
        console.log(`Minting TX sent: ${tx.hash}`);
        await tx.wait();
        return tx.hash;
    } catch (error) {
        console.error('Error minting NFT:', error);
        return null;
    }
};


const rewardReputation = async (recipientAddress, amount) => {
    if (!tokenContract) return null;
    try {
        const tx = await tokenContract.mint(recipientAddress, amount);
        console.log(`[DEBUG] Reputation Awarded: ${amount} to ${recipientAddress} (TX: ${tx.hash})`);
        return tx.hash;
    } catch (error) {
        console.error('[DEBUG] Error awarding reputation:', error);
        return null;
    }
};

const getIdentity = async (userAddress) => {
    if (!identityContract) return null;
    try {
        return await identityContract.getIdentity(userAddress);
    } catch (error) {
        console.error('[DEBUG] Error fetching identity:', error);
        return null;
    }
};

module.exports = { initBlockchain, logAttemptToBlockchain, mintCertificateNFT, rewardReputation, getIdentity };
